2023-10-31 15:58:19 | np_services.proxies | ERROR | proxies.py:104 ensure_config MainThread | Error accessing VideoMVR data path: \\W10DT714046\c$\ProgramData\AIBS_MPE\mvr\data
Traceback (most recent call last):
  File "c:\Users\ben.hardcastle\github\np_workflows\.venv\Lib\site-packages\np_services\proxies.py", line 101, in ensure_config
    _ = root.exists()
        ^^^^^^^^^^^^^
  File "C:\Users\ben.hardcastle\.pyenv\pyenv-win\versions\3.11.3\Lib\pathlib.py", line 1235, in exists
    self.stat()
  File "C:\Users\ben.hardcastle\.pyenv\pyenv-win\versions\3.11.3\Lib\pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '\\\\W10DT714046\\c$\\ProgramData\\AIBS_MPE\\mvr\\data'
